In [1]:
# N- Dimensional array

In [2]:
import numpy as np

scores=[45,45.5,23,43]
arr=np.array(scores)
print(arr)
print(arr.dtype) # .dtype return the data type of the array object

[ 45.   45.5  23.   43. ]
float64


In [3]:
scores_1=[[2,4,7],[2.3,34,5]]
arr_1=np.array(scores_1)
print(arr_1)
print(arr_1.ndim) #.ndim gives you the dimensions of an array.
print(arr_1.shape) #(number of rows, number of columns)
print(arr_1.dtype)

[[  2.    4.    7. ]
 [  2.3  34.    5. ]]
2
(2, 3)
float64


In [4]:
x=np.zeros(10) # returns a array of zeros, the same applies for np.ones(10)
x

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [5]:
y=np.ones(10)
y

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [6]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [7]:
np.eye(4) # Create a square N x N identity matrix (1’s on the diagonal and 0’s elsewhere)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [8]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
#Batch operations on data can be performed without using for loops, this is called vectorization
scores=[45,45.5,23,43]
arr=np.array(scores)
print(arr)
print(arr+arr)
print(arr-arr)
print(1/arr)
print(arr**0.5)

[ 45.   45.5  23.   43. ]
[ 90.  91.  46.  86.]
[ 0.  0.  0.  0.]
[ 0.02222222  0.02197802  0.04347826  0.02325581]
[ 6.70820393  6.74536878  4.79583152  6.55743852]


In [10]:
new_arr=np.arange(11)
print(new_arr)
print(new_arr[4])
print(new_arr[2:5])
new_arr[6:8]=69
new_arr

[ 0  1  2  3  4  5  6  7  8  9 10]
4
[2 3 4]


array([ 0,  1,  2,  3,  4,  5, 69, 69,  8,  9, 10])

In [11]:
# A major diffence between lists and array is that, array slices are views on the original array. This means that
# the data is not copied, and any modifications to the view will be reflected in the source
#  array.
modi_arr=new_arr[6:8]
modi_arr[1]=45
print(modi_arr)
print(new_arr)

[69 45]
[ 0  1  2  3  4  5 69 45  8  9 10]


In [13]:
matrix_arr=np.array([[3,4,5],[5,6,7],[7,8,9]])
print(matrix_arr)
print(matrix_arr[2])
print(matrix_arr[0,2])

[[3 4 5]
 [5 6 7]
 [7 8 9]]
[7 8 9]
5


In [ ]:
# u can change ur directory by cd path

In [15]:
# 3d arrays -> this is a 2x2x3 array
three_d_arr=np.array([[[2,3,4],[3,4,5]],[5,6,7],[6,7,8]])
print(three_d_arr)
print("returns the second list inside first list {}".format(three_d_arr[0,1]))

[[[2, 3, 4], [3, 4, 5]] [5, 6, 7] [6, 7, 8]]


IndexError: too many indices for array

In [17]:
three_d_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print (three_d_arr[0])

[[1 2 3]
 [4 5 6]]


In [19]:
copied_values = three_d_arr[0].copy() # copy arr[0] value to copied_values
three_d_arr[0]= 99  # change all values of arr[0] to 99 
print(three_d_arr)  # check the new value of three_d_arr 
three_d_arr[0] = copied_values # assign copied values back to three_d_arr[0]
print(three_d_arr)

[[[99 99 99]
  [99 99 99]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [20]:
#Import random module from Numpy 
personals = np.array(['Manu', 'Jeevan', 'Prakash', 'Manu', 'Prakash', 'Jeevan', 'Prakash'])
print(personals=='Manu')

[ True False False  True False False False]


In [22]:
from numpy import random
rand_no=random.randn(7,3)
print(rand_no)
rand_no[personals=='Manu']

[[-0.60298078 -0.14738754  1.02482888]
 [-0.30390749  1.07421934 -1.49194273]
 [-0.81251518  1.15279392  0.548894  ]
 [ 0.03537424 -0.48798893  0.09961438]
 [-1.48519799  0.44908857  0.14923537]
 [ 1.34655361  0.41607113 -1.03017568]
 [ 0.42767977 -1.56374805  0.22971342]]


array([[-0.60298078, -0.14738754,  1.02482888],
       [ 0.03537424, -0.48798893,  0.09961438]])

In [23]:
rand_no[personals=='Manu',2:] #First two columns and first two rows.

array([[ 1.02482888],
       [ 0.09961438]])

In [24]:
# To select everything except 'Manu', you can != or negate the condition using -:
print(personals!='Manu')
rand_no[-(personals=='Manu')]

[False  True  True False  True  True  True]


/Users/shashankgupta/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:2: DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
  from ipykernel import kernelapp as app


array([[-0.30390749,  1.07421934, -1.49194273],
       [-0.81251518,  1.15279392,  0.548894  ],
       [-1.48519799,  0.44908857,  0.14923537],
       [ 1.34655361,  0.41607113, -1.03017568],
       [ 0.42767977, -1.56374805,  0.22971342]])

In [25]:
# you can use boolean operator &(and), |(or)
new_var=(personals=='Manu') | (personals=='Jeevan')
print(new_var)
rand_no[new_var]

[ True  True False  True False  True False]


array([[-0.60298078, -0.14738754,  1.02482888],
       [-0.30390749,  1.07421934, -1.49194273],
       [ 0.03537424, -0.48798893,  0.09961438],
       [ 1.34655361,  0.41607113, -1.03017568]])

In [26]:
rand_no[rand_no<0]=0
rand_no

array([[ 0.        ,  0.        ,  1.02482888],
       [ 0.        ,  1.07421934,  0.        ],
       [ 0.        ,  1.15279392,  0.548894  ],
       [ 0.03537424,  0.        ,  0.09961438],
       [ 0.        ,  0.44908857,  0.14923537],
       [ 1.34655361,  0.41607113,  0.        ],
       [ 0.42767977,  0.        ,  0.22971342]])

In [27]:
rand_no[personals=='Manu']=90
rand_no

array([[ 90.        ,  90.        ,  90.        ],
       [  0.        ,   1.07421934,   0.        ],
       [  0.        ,   1.15279392,   0.548894  ],
       [ 90.        ,  90.        ,  90.        ],
       [  0.        ,   0.44908857,   0.14923537],
       [  1.34655361,   0.41607113,   0.        ],
       [  0.42767977,   0.        ,   0.22971342]])

In [ ]:
# Fancy Indexing(Indexing using integer arrays)

In [28]:
from numpy import random
x=random.randn(7,4)
for j in range(7):
    x[j]=j
x

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.]])

In [30]:
# To select a subset of rows in particular order, you can simply pass a list.
x[[4,6,1]]

array([[ 4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.],
       [ 1.,  1.,  1.,  1.]])

In [31]:
fab=np.arange(36).reshape(9,4) #reshape is to reshape an array
print(fab)
fab[[1,4,3,2],[3,2,1,0]] #the position of the output array are[(1,3),(4,2),(3,1),(2,0)]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]


array([ 7, 18, 13,  8])

In [33]:
fab[[1, 4, 8, 2]][:, [0, 3, 1, 2]] # entire first row is selected, but the elements are interchanged, same goes for 4th, 8th and 2 nd row

array([[ 4,  7,  5,  6],
       [16, 19, 17, 18],
       [32, 35, 33, 34],
       [ 8, 11,  9, 10]])

In [34]:
# another way to do the above operation is by using np.ix_ function.
fab[np.ix_([1,4,8,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [16, 19, 17, 18],
       [32, 35, 33, 34],
       [ 8, 11,  9, 10]])

In [35]:
# Transposing Arrays
transpose=np.arange(12).reshape(3,4)
transpose.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [36]:
#you can use np.dot function to perform matrix computations. You can calculate X transpose X as follows:
np.dot(transpose.T,transpose)

array([[ 80,  92, 104, 116],
       [ 92, 107, 122, 137],
       [104, 122, 140, 158],
       [116, 137, 158, 179]])

In [ ]:
# universal functions

In [37]:
funky=np.arange(8)
print(np.sqrt(funky))
print(np.exp(funky))#exponent of the array
# these are called as unary functions

[ 0.          1.          1.41421356  1.73205081  2.          2.23606798
  2.44948974  2.64575131]
[  1.00000000e+00   2.71828183e+00   7.38905610e+00   2.00855369e+01
   5.45981500e+01   1.48413159e+02   4.03428793e+02   1.09663316e+03]


In [38]:
x=random.randn(10)
y=random.randn(10)
print(x)
print(y)
print(np.maximum(x,y))
print(np.modf(x))

[-0.17304237  0.46594772 -0.35502472 -1.53156041  1.05449394 -0.08508312
  0.29916096  1.71424178  1.43565019  0.76670041]
[ 0.82488037  0.87106557 -1.44268697  1.94885964 -1.33153801 -0.6775069
 -0.49443182  0.91673476 -2.73398249 -0.06720278]
[ 0.82488037  0.87106557 -0.35502472  1.94885964  1.05449394 -0.08508312
  0.29916096  1.71424178  1.43565019  0.76670041]
(array([-0.17304237,  0.46594772, -0.35502472, -0.53156041,  0.05449394,
       -0.08508312,  0.29916096,  0.71424178,  0.43565019,  0.76670041]), array([-0.,  0., -0., -1.,  1., -0.,  0.,  1.,  1.,  0.]))


In [ ]:
# Data processing using Arrays

In [40]:
mtrices=np.arange(-5,5,1)
print(mtrices)
x,y=np.meshgrid(mtrices,mtrices)
print(x)
print(y)

[-5 -4 -3 -2 -1  0  1  2  3  4]
[[-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]]
[[-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]
 [-4 -4 -4 -4 -4 -4 -4 -4 -4 -4]
 [-3 -3 -3 -3 -3 -3 -3 -3 -3 -3]
 [-2 -2 -2 -2 -2 -2 -2 -2 -2 -2]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 2  2  2  2  2  2  2  2  2  2]
 [ 3  3  3  3  3  3  3  3  3  3]
 [ 4  4  4  4  4  4  4  4  4  4]]


In [42]:
x1=np.array([1,2,3,4,5])
x2=np.array([5,6,7,8,9])
cond =[True, False, True, True, False]
z1=[(x,y,z) for x,y,z in zip(x1,x2,cond)] # zip
print(z1)
np.where(cond,x1,x2)

[(1, 5, True), (2, 6, False), (3, 7, True), (4, 8, True), (5, 9, False)]


array([1, 6, 3, 4, 9])

In [43]:
ra=np.random.randn(5,5)
print(ra)
print(np.where(ra>0,1,-1))

[[-0.30369228 -1.47562253  0.92431313 -1.20339922  0.12543659]
 [ 1.3465828   1.39497786 -0.15707045  0.8936959  -0.11382046]
 [ 0.15259248  0.00506223 -1.45192589 -0.83550225  1.55632705]
 [-0.24778125 -0.51671494 -0.6334234  -2.32867396 -0.30773003]
 [ 0.95772505  0.20512622  2.26262704 -0.09836975  0.76456636]]
[[-1 -1  1 -1  1]
 [ 1  1 -1  1 -1]
 [ 1  1 -1 -1  1]
 [-1 -1 -1 -1 -1]
 [ 1  1  1 -1  1]]


In [ ]:
# Statistical methods

In [45]:
thie=np.random.randn(5,5)
print(thie.mean())
print(np.mean(thie))
print(thie.sum())

-0.0106601832451
-0.0106601832451
-0.266504581127


In [46]:
jp=np.arange(12).reshape(4,3)
print(jp)
print(np.sum(jp,axis=0))#axis =0, gives you sum of the columns. axis =1 , gives sum of rows.
# remember this zero is for columns and one is for rows.

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[18 22 26]


In [47]:
print(np.sum(jp,axis=1))

[ 3 12 21 30]


In [48]:
jp.cumsum(0)#cumulative sum of columns, try the same for jp.cumprod(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15],
       [18, 22, 26]])

In [49]:
jp.cumsum(1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21],
       [ 9, 19, 30]])

In [50]:
xp=np.random.randn(100)
print((xp>0).sum())
print((xp<0).sum())
tandf =np.array([True,False,True,False,True,False])
print(tandf.any()) #checks if any of the values are true
print(tandf.all()) #returns false even if a single value is false

54
46
True
False


In [ ]:
# Sorting

In [51]:
lp=np.random.randn(8)
print(lp)
lp.sort()
lp

[ 0.84841226  0.72772059 -0.341379    1.12544025  0.29742683 -0.98227762
  0.10863881  1.47484016]


array([-0.98227762, -0.341379  ,  0.10863881,  0.29742683,  0.72772059,
        0.84841226,  1.12544025,  1.47484016])

In [52]:
tp=np.random.randn(4,4)
tp

array([[-0.60457641,  0.07964682, -1.26085893,  0.44920061],
       [-0.21118148,  0.7413414 ,  0.99589915,  0.30758687],
       [ 1.15008575,  0.33109572, -0.51430416,  0.27436219],
       [ 0.57816019,  0.55969757, -0.94759417,  1.92340907]])

In [53]:
tp.sort(1)
tp

array([[-1.26085893, -0.60457641,  0.07964682,  0.44920061],
       [-0.21118148,  0.30758687,  0.7413414 ,  0.99589915],
       [-0.51430416,  0.27436219,  0.33109572,  1.15008575],
       [-0.94759417,  0.55969757,  0.57816019,  1.92340907]])

In [54]:
personals = np.array(['Manu', 'Jeevan', 'Prakash', 'Manu', 'Prakash', 'Jeevan', 'Prakash'])
np.unique(personals) # returns the unique elements in the array

array(['Jeevan', 'Manu', 'Prakash'], 
      dtype='<U7')

In [55]:
set(personals)

{'Jeevan', 'Manu', 'Prakash'}

In [56]:
np.in1d(personals,['Manu']) #in1d function checks for the value 'Manu' and returns True, other wise returns False

array([ True, False, False,  True, False, False, False], dtype=bool)

In [ ]:
# Linear Algebra

In [57]:
cp = np.array([[1,2,3],[4,5,6]])
dp = np.array([[7,8],[9,10],[11,12]])
print(cp)
print(dp)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [58]:
cp.dot(dp) # element wise multiplication

array([[ 58,  64],
       [139, 154]])

In [59]:
np.dot(cp,np.ones(3))

array([  6.,  15.])

In [60]:
# numpy.linalg has standard matrix operations like determinants and inverse.
from numpy.linalg import inv,qr
cp = np.array([[1,2,3],[4,5,6]])
new_mat=cp.T.dot(cp)
print(new_mat)

[[17 22 27]
 [22 29 36]
 [27 36 45]]


In [61]:
sp=np.random.randn(5,5)
rt=inv(sp)
print(rt)

[[ -6.03123684  -7.93923096  35.95869941  17.0023185   11.31012449]
 [ -2.12920628  -3.41083139  14.54220546   6.58409449   4.47993982]
 [  3.73788707   5.21322166 -25.32896345 -12.21031999  -8.03406224]
 [ -2.97572694  -4.38168613  19.11844184   9.45844135   5.83557845]
 [  9.54058322  12.93548546 -60.05779112 -28.2733284  -18.45324188]]


In [64]:
# to calculate the product of a matrix and its inverse
sp.dot(rt)

array([[  1.00000000e+00,   7.23187352e-16,   1.25908763e-14,
          5.61650905e-15,   6.95113438e-15],
       [  1.43963722e-15,   1.00000000e+00,  -1.62601903e-14,
          5.74007467e-16,  -3.03031226e-15],
       [ -1.49875176e-15,  -7.97761683e-16,   1.00000000e+00,
          5.33343375e-15,   5.87587943e-15],
       [  1.52994963e-15,   3.58093923e-16,  -1.40918121e-14,
          1.00000000e+00,  -2.94721238e-15],
       [  2.98826939e-16,   3.41008679e-15,   6.13360276e-15,
          1.73032916e-15,   1.00000000e+00]])

In [65]:
q,r=qr(sp)
print(q)
r

[[-0.45638124  0.66760259  0.54216219 -0.18411257 -0.13485424]
 [-0.24830593 -0.57167744  0.60557716  0.45975508 -0.1828405 ]
 [-0.3568029   0.09503963 -0.08076395  0.36945481  0.84890487]
 [-0.01629499 -0.39804931  0.31696048 -0.76231022  0.39963785]
 [ 0.77620003  0.24498144  0.48202667  0.19265021  0.26083289]]


array([[ 2.52780914,  0.43920003, -0.82078198, -0.33947685,  1.86386738],
       [ 0.        ,  2.58247572, -0.74433736,  0.0448749 ,  0.95193453],
       [ 0.        ,  0.        , -1.94702153, -0.4416885 ,  0.68188331],
       [ 0.        ,  0.        ,  0.        , -2.04384282, -0.65677648],
       [ 0.        ,  0.        ,  0.        ,  0.        , -0.0141348 ]])